### ISSUE TITLE
Stop auto-playing all the things.

### ISSUE THREAD

**Issue by nouvieux** [andrewbrey/netflix-tweaked#12]
Netflix has started auto-playing video when hovering over any card. It is very frustrating. Make it stop please!

**Comment by andrewbrey** [comment]
@nouvieux Thanks, I'll try to get to this over the weekend 😃

**Comment by andrewbrey** [comment]
@nouvieux I just pushed version 1.0.12 out to the web store - please update and give it a try and let me know if you observe that this is resolved.

**Comment by nouvieux** [comment]
Works perfectly! Thanks for the really quick turnaround!
