### ISSUE TITLE
Feature suggestion:  Bring in IMDB score

### ISSUE THREAD

**Issue by BenjaminInUt** [andrewbrey/netflix-tweaked#14]
Feature suggestion:  Bring in IMDB score and link to IMDB page.
(Since reviews are now gone)

**Comment by andrewbrey** [comment]
@BenjaminInUt I didn't realize that reviews are gone now, I have not been paying much attention to Netflix or this extension recently - life has gotten in the way 0_o

This is a good idea, I think it would not be too bad to implement, and perhaps also provide links out to a configurable set of other review sources like Rotten Tomatoes, Metacritic, Etc...

I don't know when I'll get to this, but I will eventually. In the mean time, definitely feel free to open a pull request!

Cheers!

**Comment by andrewbrey** [comment]
@BenjaminInUt I've found some time to come back to this project and try and improve it, and I spent some time thinking more about your feature request here. I found a way that I could pretty easily, but ultimately unreliably, search out and add the IMDB ratings for a given show. The summary of what I found is that when my search for the movie/show returns the correct results, this would be very handy, but there is not a reliable way for me to programmatically guarantee that the rating I'm showing (if I am able to find one at all) is even for the right movie. I've come to the conclusion that this is a bigger request than it seems on the surface, and ultimately it's not what this extension was built to do. My goal with it isn't to solve every pain point / annoyance with the Netflix interface, it's really meant to address two very specific ones, being the reordering of your watch lists and the prevention of auto-trailers.

I've labeled this issues as "won't fix" as I think in the end, it's not something I want to be in scope for this extension - hopefully you can understand why I don't want feature creep to make it even harder for me to keep this extension up to date :)
