### ISSUE TITLE
Not working for me, multiple issues

### ISSUE THREAD

**Issue by maxinecharles** [andrewbrey/netflix-tweaked#15]
When I'm on the NetFlix site, if I hover over any video image I get the preview, so the extension isn't working. 

if I hover over the NT extension icon it says "NetFlix Tweaked is inactive." If I go into extensions it is turned on.

If I click on the NT icon I can see that 'options' is greyed out. 

I've tried choosing both 'on NetFlix.com' and 'when I click the extension.' No change.

 - OS: Windows 7
 - Browser Chrome
 - Version 1.0.13

**Comment by andrewbrey** [comment]
@maxinecharles Thanks for the issue report. I have limited time lately to devote to maintenance of this project, but I will do my best to get to it as soon as possible.

**Comment by maxinecharles** [comment]
Kind of you, Andrew, thanks.

**Comment by andrewbrey** [comment]
Please upgrade to version 1.0.15 to resolve this issue. 

Cheers!
