### ISSUE TITLE
A way to filter out unwanted shows in netflix menu

### ISSUE THREAD

**Issue by yarba87** [andrewbrey/netflix-tweaked#4]
Looking for a way to filter out programs in the netflix menu that you dont want to watch/see to make finding something you want to see easier. 
Block / filter out previous watched shows, different languages without english audio (ability to select, say for instance foreign films with no spanish audio), genres (ex...no horror), shows that you start and were bad so you stopped them, low imdb/rotten tomato scores, and just programs you dont have interest in seeing.
Thanks

**Comment by andrewbrey** [comment]
@yarba87 I've found some time to come back to this project and try and improve it, and I spent some time thinking more about your feature request here. My goal with this extension isn't to solve every pain point / annoyance with the Netflix interface, it's really meant to address two very specific ones, being the reordering of your watch lists and the prevention of auto-trailers.

I've labeled this issues as "won't fix" as I think in the end, it's not something I want to be in scope for this extension - hopefully you can understand why I don't want feature creep to make it even harder for me to keep this extension up to date :)
